---
title: "Intro to reactR"
author: "Kent Russell & Harry Anderson"
date: "`r Sys.Date()`"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Intro to reactR}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

## Why reactR

[`React`](https://reactjs.org/) is a JavaScript library for building user interfaces.
The `{shiny}` package provides us with functions like `sliderInput()` and `selectInput()` to help us to easily implement common UI features in our Shiny apps.
These functions are easy to use, and _most_ of the time they'll be all we need to build-out our prototypes.
But seasoned web developers know that there's a world of UI potential beyond what `{shiny}` gives us out-of-the-box, and while packages like `[{shinydashboard}](https://github.com/rstudio/shinydashboard)` expand the libary of UI elements at our disposal, they only go so far.

The React ecosystem, on the other hand, has every piece of UI that we could ever imagine.
The only problem is that React is a JavaScript (not an R) library.
Enter: `{reactR}`, which binds React components to R functions, and makes our Shiny apps really shine. 

If you don't know anything about React, then you should brush-up on it by going through the [official tutorial](https://reactjs.org/tutorial/tutorial.html).
You'll need to be familliar with the basics of JavaScript modules, React components and JSX in order to properly understand the rest of this tutorial.


## Installation

```
install.packages("reactR")

# for the latest development version
#  install from Github
# devtools::install_github("timelyportfolio/reactR")
```

---

## A quick example
### Using React to render a simple `h1` HTML element below

<div id="react-heading-here"></div>

```{r}
library(reactR)
library(htmltools)

attachDependencies(
  tags$script(
  "
    ReactDOM.render(
      React.createElement(
        'h1',
        null,
        'Powered by React'
      ),
      document.getElementById('react-heading-here')
    )
  "
  ),
  html_dependency_react()
)
```

---

## A complex example
### Creating our own React component, and integrating it into a Shiny app

## Requirements

In addition to having our Shiny development environment up-and-running, we'll also need to have [Node and NPM](https://nodejs.org/en/download/) installed.

## Blog Post

For more on how we can use R and React, see the blog post [React in R](https://www.jsinr.me/2017/11/19/react-in-r/).  Also, there are many more examples in the Github repo at [inst/examples](https://github.com/react-R/reactR/tree/master/inst/examples).

## Using JSX

[`JSX`](https://reactjs.org/docs/jsx-in-depth.html) helps ease some of the burden caused by `React.createElement`.  `reactR` provides a `babel_transform()` function to use `JSX`.  Hopefully, in the future, we can convince RStudio to modify `htmltools` to work directly with `JSX` (see [issue](https://github.com/rstudio/htmltools/pull/72)).
